name: CI_CD_BasicWorkflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  build:

    runs-on: windows-latest
    env:
      solutionPath: '.\WinNetCoreApp'

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ${{ env.solutionPath }}
    - name: Build
      run: dotnet build ${{ env.solutionPath }} --no-restore
    - name: Test
      run: dotnet test ${{ env.solutionPath }} --no-build --verbosity normal
  
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - run: echo test

  deploy_client: 
    runs-on: ubuntu-latest
    environment: prod
    needs: [test, deploy_server]
    steps:
    - run: echo test

  deploy_server:
    runs-on: ubuntu-latest
    environment: prod
    needs: test
    steps:
    - run: echo ${{secrets.MySecret}}
